#!/usr/bin/env bash
# Resolve docker/modern/requirements-${A:-a1}.in inside the pinned base image and write
# requirements-${A:-a1}.lock with every package the resolver added or changed relative to the
# base (the base's own packages stay pinned by the image digest). Rerun only on purpose:
# a new lock is a new environment and needs the phase-A equivalence tests again.
set -euo pipefail
HERE="$(cd "$(dirname "$0")" && pwd)"
BASE="pytorch/pytorch@sha256:68c022c2f4627943a6f3e574cfd2c8ae4256210d5f66ae2b117942e0a8d4fa9d"
docker run --rm -e A="${A:-a1}" -v "$HERE":/w -w /w "$BASE" bash -c '
set -euo pipefail
pip freeze --all | sort > /tmp/before
pip install --quiet --no-cache-dir -r requirements-${A:-a1}.in -f https://data.dgl.ai/wheels/torch-2.4/cu121/repo.html
pip freeze --all | sort > /tmp/after
{ echo "# generated by docker/modern/lock.sh from requirements-${A:-a1}.in on $(date -u +%Y-%m-%d)";
  echo "# packages added or changed relative to the base image; install with --no-deps";
  comm -13 /tmp/before /tmp/after; } > requirements-${A:-a1}.lock
comm -23 /tmp/before /tmp/after | sed "s/^/replaced from base: /" >&2
pip check'
cat "$HERE/requirements-${A:-a1}.lock"
